#!/bin/bash
curl -H "Content-Type: application/json" -X POST -d '{"player_id":"68b19bbe-bc2a-400f-b4e7-6e632b3b908f", "receiver_id":"8673cc53-e2a8-4375-b6a3-007e2ebe6d5f", "mail_id":"'$1'", "content":"this is a reply"}' http://localhost:1337/api/reply_mail | python -m json.tool
