#!/bin/sh
curl -H "Content-Type: application/json" -X POST -d '{"sender_id":"8673cc53-e2a8-4375-b6a3-007e2ebe6d5f", "receiver_id":"68b19bbe-bc2a-400f-b4e7-6e632b3b908f", "content":"the very first in game mail, with random character asldjf;laskdjf;laskdjf;aslkjdf;lkdjf;lkdjf;laksjdf;laskjdf;lkdjf;lkdjsa;lkdjf;alksdjf"}' http://localhost:1337/api/send_mail

