#!/bin/sh
curl -H "Content-Type: application/json" -X POST -d '{"sender_id":"8673cc53-e2a8-4375-b6a3-007e2ebe6d5f", "receiver_id":"68b19bbe-bc2a-400f-b4e7-6e632b3b908f", "content":"attached", "attachment":[{"item_id":"1", "item_qty":"500"}, {"item_id":"2", "item_qty":"350"}]}' http://localhost:1337/api/send_mail_attachment

